food= ["carrot", "banana", "burger", "chocolate", "lemon"]
console.log(food)
console.log("Essas são minhas comidas favoritas")
console.log(food[0])
console.log(food[1])
console.log(food[2])
console.log(food[3])
console.log(food[4])
food[1] = prompt("qual sua comida favorita")
console.log(food)
